modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MrMelon54/draggable_lists/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "draggable_lists"
version = "${version}"
displayName = "Draggable Lists"
authors = "MrMelon54"
description = "Draggable resource packs, datapacks and servers"
logoFile = "icon.png"

[[mixins]]
config = "draggable_lists.mixins.json"

[[dependencies.draggable_lists]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.draggable_lists]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.draggable_lists]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.0,)"
ordering = "AFTER"
side = "BOTH"
