modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/MrMelon54/draggable_lists/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "draggable_lists"
version = "${version}"
displayName = "Draggable Lists"
authors = "MrMelon54"
description = "Draggable resource packs, datapacks and servers"
logoFile = "icon.png"

[[mixins]]
config = "draggable_lists.mixins.json"

[[dependencies.draggable_lists]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
